### ISSUE TITLE
The Password of Pre-train model download

### ISSUE THREAD

**Issue by Orbis36** [Yiming992/Test-Linking-Segments-Text-Localization#1]
Thanks for your work
May I have the password of the link：https://pan.baidu.com/share/init?surl=nvuWqlr to download the model？

**Comment by Yiming992** [comment]
I think the password is isme, and you can refer to this [issue](https://github.com/bgshih/seglink/issues/4)

**Comment by Orbis36** [comment]
Great！Thanks again
